language: java
jdk:
  - openjdk13
branches:
  only:
    - master
git:
  submodules: false

before_install:
  - echo -e "\n\nmachine api.github.com\nlogin blessing333\npassword $CI_USER_TOKEN\n" > ~/.netrc
  - cat ~/.netrc
  - git submodule update --init --recursive

notifications:
  email:
    recipients: 'blessing_333@naver.com'
