language: java
jdk:
  - openjdk13
branches:
  only:
    - master
git:
  submodules: false

before_install:
  - wget -q -O - https://raw.githubusercontent.com/mlocati/travisci-github-deploy-key/master/load-deploy-key.sh | sh
  - git submodule update --init --recursive

notifications:
  email:
    recipients: 'blessing_333@naver.com'
