language: java
jdk:
  - openjdk13
branches:
  only:
    - master
git:
  submodules: false
before_install:
  - echo -e "\n\nmachine api.github.com\nlogin blessing333\npassword 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\n" > ~/.netrc
  - curl -n https://api.github.com/user
  - git submodule update --init --recursive
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
notifications:
  email:
    recipients: 'blessing_333@naver.com'
